DROP DATABASE IF EXISTS movie_mania;
CREATE DATABASE movie_mania;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
);


-- TODO: SETUP A WAY TO STORE FAVORITE MOVIES
-- TODO: 